/**
 * Detect whether a directory looks like a generated ADK project.
 */

import { safeExists, safeReadFile } from "./fs-safe.js";

export interface ProjectInfo {
  valid: boolean;
  agentName: string | null;
  template: "basic" | "mcp" | "sequential" | "unknown" | null;
  error?: string;
}

/**
 * Inspect a directory and determine if it contains a recognized ADK project
 * generated by this extension.
 */
export function detectAdkProject(projectRoot: string): ProjectInfo {
  // Check for the .adk-scaffold marker
  const marker = safeReadFile(projectRoot, ".adk-scaffold");
  if (!marker) {
    // Fallback: look for agent.py in any immediate subdirectory
    const hasEnvExample = safeExists(projectRoot, ".env.example");
    if (!hasEnvExample) {
      return { valid: false, agentName: null, template: null, error: "Not a recognized ADK project (no .adk-scaffold marker or .env.example)" };
    }
    return { valid: true, agentName: null, template: "unknown" };
  }

  try {
    const info = JSON.parse(marker);
    return {
      valid: true,
      agentName: info.name ?? null,
      template: info.template ?? "unknown",
    };
  } catch {
    return { valid: true, agentName: null, template: "unknown" };
  }
}
