/**
 * Detect whether a directory looks like a generated ADK project.
 */

import { safeExists, safeReadFile } from "./fs-safe.js";
import { MANIFEST_FILENAME } from "./scaffold-manifest.js";

export interface ProjectInfo {
  valid: boolean;
  agentName: string | null;
  template: "basic" | "mcp" | "sequential" | "unknown" | null;
  error?: string;
}

/**
 * Inspect a directory and determine if it contains a recognized ADK project
 * generated by this extension.
 */
export function detectAdkProject(projectRoot: string): ProjectInfo {
  // Primary: check for .adk-scaffold.json
  const manifest = safeReadFile(projectRoot, MANIFEST_FILENAME);
  if (manifest) {
    return parseMarker(manifest);
  }

  // Legacy fallback: check for .adk-scaffold (pre-0.1.0)
  const legacy = safeReadFile(projectRoot, ".adk-scaffold");
  if (legacy) {
    return parseMarker(legacy);
  }

  // Heuristic fallback: look for .env.example
  const hasEnvExample = safeExists(projectRoot, ".env.example");
  if (!hasEnvExample) {
    return {
      valid: false,
      agentName: null,
      template: null,
      error: "Not a recognized ADK project (no .adk-scaffold.json marker or .env.example)",
    };
  }
  return { valid: true, agentName: null, template: "unknown" };
}

function parseMarker(raw: string): ProjectInfo {
  try {
    const info = JSON.parse(raw);
    return {
      valid: true,
      agentName: info.name ?? null,
      template: info.template ?? "unknown",
    };
  } catch {
    return { valid: true, agentName: null, template: "unknown" };
  }
}
