/**
 * Detect whether a directory looks like a generated ADK project.
 */

import { readdirSync, statSync } from "node:fs";
import { safeExists, safeReadFile } from "./fs-safe.js";
import { MANIFEST_FILENAME } from "./scaffold-manifest.js";
import { CREATION_METADATA_FILENAME, readAndValidateMetadata } from "./creation-metadata.js";

export interface ProjectInfo {
  valid: boolean;
  agentName: string | null;
  template: "basic" | "mcp" | "sequential" | "native_app" | "native_config" | "official_sample" | "unknown" | null;
  /** Detection source: "manifest", "pi-metadata", "heuristic". */
  detectedVia?: string;
  error?: string;
}

/**
 * Inspect a directory and determine if it contains a recognized ADK project
 * generated by this extension or created via native ADK CLI.
 */
export function detectAdkProject(projectRoot: string): ProjectInfo {
  // Primary: check for .adk-scaffold.json (legacy Pi-scaffolded projects)
  const manifest = safeReadFile(projectRoot, MANIFEST_FILENAME);
  if (manifest) {
    return parseMarker(manifest, "manifest");
  }

  // Native creation metadata: .pi-adk-metadata.json (Phase 5A: validated)
  const piMetaValidation = readAndValidateMetadata(projectRoot);
  if (piMetaValidation.ok && piMetaValidation.metadata) {
    return {
      valid: true,
      agentName: piMetaValidation.metadata.agent_name || null,
      template: (piMetaValidation.metadata.source_type as ProjectInfo["template"]) ?? "unknown",
      detectedVia: "pi-metadata",
    };
  }
  // Fall through if validation failed but file existed — check if file is present but malformed
  const piMetadata = safeReadFile(projectRoot, CREATION_METADATA_FILENAME);
  if (piMetadata) {
    // File exists but failed validation — still treat as detected but with unknown shape
    return { valid: true, agentName: null, template: "unknown", detectedVia: "pi-metadata" };
  }

  // Legacy fallback: check for .adk-scaffold (pre-0.1.0)
  const legacy = safeReadFile(projectRoot, ".adk-scaffold");
  if (legacy) {
    return parseMarker(legacy, "manifest");
  }

  // Heuristic fallback: look for .env.example
  const hasEnvExample = safeExists(projectRoot, ".env.example");
  if (hasEnvExample) {
    return { valid: true, agentName: null, template: "unknown", detectedVia: "heuristic" };
  }

  // Heuristic: native ADK projects typically have a subdirectory with agent.py
  if (hasAgentSubdir(projectRoot)) {
    return {
      valid: true,
      agentName: findAgentSubdirName(projectRoot),
      template: "unknown",
      detectedVia: "heuristic",
    };
  }

  return {
    valid: false,
    agentName: null,
    template: null,
    error:
      "Not a recognized ADK project (no .adk-scaffold.json, .pi-adk-metadata.json, " +
      ".env.example, or recognizable ADK structure)",
  };
}

// ---------------------------------------------------------------------------
// Parsers
// ---------------------------------------------------------------------------

function parseMarker(raw: string, via: string): ProjectInfo {
  try {
    const info = JSON.parse(raw);
    return {
      valid: true,
      agentName: info.name ?? null,
      template: info.template ?? "unknown",
      detectedVia: via,
    };
  } catch {
    return { valid: true, agentName: null, template: "unknown", detectedVia: via };
  }
}

function parsePiMetadata(raw: string): ProjectInfo {
  try {
    const meta = JSON.parse(raw);
    return {
      valid: true,
      agentName: meta.agent_name ?? null,
      template: meta.source_type ?? "unknown",
      detectedVia: "pi-metadata",
    };
  } catch {
    return { valid: true, agentName: null, template: "unknown", detectedVia: "pi-metadata" };
  }
}

// ---------------------------------------------------------------------------
// Agent subdirectory heuristic
// ---------------------------------------------------------------------------

function hasAgentSubdir(projectRoot: string): boolean {
  return findAgentSubdirName(projectRoot) !== null;
}

function findAgentSubdirName(projectRoot: string): string | null {
  try {
    const entries = readdirSync(projectRoot);
    for (const entry of entries) {
      if (entry.startsWith(".")) continue;
      try {
        const entryPath = `${projectRoot}/${entry}`;
        if (statSync(entryPath).isDirectory()) {
          if (
            safeExists(projectRoot, `${entry}/agent.py`) ||
            safeExists(projectRoot, `${entry}/__init__.py`)
          ) {
            return entry;
          }
        }
      } catch {
        continue;
      }
    }
  } catch {
    // directory not readable
  }
  return null;
}
